import unittest
import os
import sys

# Add root folder to sys.path to enable smooth imports in testing
basedir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
if basedir not in sys.path:
    sys.path.insert(0, basedir)

from updater import parse_version
from config import Config
from app import create_app
from extensions import db
from models import Settings

class TestUpdaterLogic(unittest.TestCase):
    
    def test_parse_version_standard(self):
        """Test semver parsing of standard tags."""
        self.assertEqual(parse_version("1.2.3"), (1, 2, 3))
        self.assertEqual(parse_version("v1.2.3"), (1, 2, 3))
        self.assertEqual(parse_version("V2.0.1"), (2, 0, 1))

    def test_parse_version_partial(self):
        """Test semver parsing of incomplete version tags."""
        self.assertEqual(parse_version("1"), (1, 0, 0))
        self.assertEqual(parse_version("v1.2"), (1, 2, 0))
        self.assertEqual(parse_version(None), (0, 0, 0))
        self.assertEqual(parse_version(""), (0, 0, 0))

    def test_parse_version_complex(self):
        """Test semver parsing of prerelease tags or alphanumeric tags."""
        self.assertEqual(parse_version("v1.2.3-alpha"), (1, 2, 3))
        self.assertEqual(parse_version("2.1.0.4-beta"), (2, 1, 0))
        self.assertEqual(parse_version("version-3.4.5"), (3, 4, 5))

    def test_version_comparison(self):
        """Test that tuples generated by parse_version compare correctly using standard semver rules."""
        self.assertTrue(parse_version("1.2.3") > parse_version("1.2.2"))
        self.assertTrue(parse_version("2.0.0") > parse_version("1.9.9"))
        self.assertTrue(parse_version("v1.10.2") > parse_version("v1.2.9"))
        self.assertFalse(parse_version("1.2.2") > parse_version("1.2.2"))

    def test_settings_integration(self):
        """Test that update checker settings fall back correctly or load as expected within application context."""
        app = create_app()
        app.config['TESTING'] = True
        app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///:memory:'
        
        with app.app_context():
            db.create_all()
            
            # Verify clean db state
            check_enabled = Settings.query.filter_by(key='check_for_updates').first()
            self.assertIsNone(check_enabled)
            
            # Seed value
            setting = Settings(key='check_for_updates', value='false')
            db.session.add(setting)
            db.session.commit()
            
            # Retrieve value
            check_enabled = Settings.query.filter_by(key='check_for_updates').first()
            self.assertIsNotNone(check_enabled)
            self.assertEqual(check_enabled.value, 'false')
            
            db.drop_all()

if __name__ == '__main__':
    unittest.main()
