"""remove_nickname_column

Revision ID: 1f09cf13b784
Revises: d023b30597ac
Create Date: 2026-05-23 08:34:03.772734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f09cf13b784'
down_revision = 'd023b30597ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
