"""Add Person model and person_id to Account

Revision ID: d023b30597ac
Revises: 3d4e28112a3d
Create Date: 2026-05-23 08:12:54.993154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd023b30597ac'
down_revision = '3d4e28112a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    person_table = op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_account_person', 'person', ['person_id'], ['id'])

    # Data migration: insert a default person and update existing accounts
    op.bulk_insert(person_table, [{'name': 'Default Person'}])
    op.execute('UPDATE account SET person_id = (SELECT id FROM person WHERE name = "Default Person" LIMIT 1)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('person_id')

    op.drop_table('person')
    # ### end Alembic commands ###
