# -*- mode: python ; coding: utf-8 -*-

import os

block_cipher = None

# This spec lives in packaging/; every source path is anchored to the repository root.
ROOT = os.path.dirname(SPECPATH)

# Include necessary static files, templates, migrations, default valuations, and dynamic plugins
added_files = [
    (os.path.join(ROOT, src), dest) for src, dest in [
        ('templates', 'templates'),
        ('static', 'static'),
        ('migrations', 'migrations'),
        ('plugins', 'plugins'),
        ('valuations.default.json', '.'),
        ('settings.default.json', '.'),
        ('version.txt', '.'),
        ('LICENSE', '.'),
        ('NOTICE', '.'),
    ]
]

a = Analysis(
    [os.path.join(ROOT, 'main.py')],
    pathex=[ROOT],
    binaries=[],
    datas=added_files,
    hiddenimports=[
        'sqlalchemy',
        'flask_sqlalchemy',
        'flask_migrate',
        'cryptography',
        'apscheduler',
        'seleniumbase',
        'certifi',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='awardtracker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch='universal2' if (__import__('sys').platform == 'darwin' and __import__('os').environ.get('AWARDTRACKER_BUILD_UNIVERSAL') == '1') else None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(SPECPATH, 'awardtracker.ico'),
)

import sys
if sys.platform == 'darwin':
    app = BUNDLE(
        exe,
        name='AwardTracker.app',
        # packaging/awardtracker.icns is generated by scripts/build-macos.sh from
        # static/favicon.png using macOS-native sips + iconutil before PyInstaller runs.
        icon=os.path.join(SPECPATH, 'awardtracker.icns'),
        bundle_identifier='com.awardtracker.app',
        info_plist={
            'NSPrincipalClass': 'NSApplication',
            'NSAppleScriptEnabled': False,
        },
    )

